type Query {
	book(id: ID!): Book
	bookList(filter: BookInput): [Book]
}

type Mutation {
	deleteBook(id: ID!): Boolean
}

type Book {
	id: ID!
	name: String
	genre: String
}

input BookInput {
	id: ID!
	name: String
	genre: String
}
